# 服务配置
server:
  port: ":45613"
  mode: debug # debug, release, test
  read_timeout: 60s
  write_timeout: 60s

# 数据库配置
database:
  driver: mysql
  host: localhost
  port: 3306
  database: go_demo
  username: root
  password: qweR123!! # 建议使用环境变量 DB_PASSWORD
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 60 # 分钟

# mongodb配置
mongodb:
  host: localhost
  port: 27017
  database: go_demo
  username: admin
  password: qweR123!! # 建议使用环境变量 MONGO_PASSWORD
  auth_source: "admin"
  max_pool_size: 100
  min_pool_size: 10


# Redis配置
redis:
  host: localhost
  port: 6379
  password: "" # 建议使用环境变量 REDIS_PASSWORD
  db: 0
  pool_size: 10
  min_idle_conns: 5

# JWT配置
jwt:
  secret: "b9a0c569-9d0a-461e-adbb-cb1821fda692" # 建议使用环境变量 JWT_SECRET
  expire_hours: 24
  issuer: "go-demo"

# 日志配置
log:
  level: debug # debug, info, warn, error
  file_path: logs/app.log
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # 天
  compress: true

